#!/bin/bash

cd /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-pad_q/execution
tmpDir=$(mkdir -p "/cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-pad_q/tmp.e8705854" && echo "/cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-pad_q/tmp.e8705854")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-pad_q/execution

)
out1f05a7e4="${tmpDir}/out.$$" err1f05a7e4="${tmpDir}/err.$$"
mkfifo "$out1f05a7e4" "$err1f05a7e4"
trap 'rm "$out1f05a7e4" "$err1f05a7e4"' EXIT
touch '/cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-pad_q/execution/stdout' '/cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-pad_q/execution/stderr'
tee '/cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-pad_q/execution/stdout' < "$out1f05a7e4" &
tee '/cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-pad_q/execution/stderr' < "$err1f05a7e4" >&2 &
(
cd /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-pad_q/execution


set -euo pipefail

awk -v pad=200000 'BEGIN{OFS="\t"} \
{
  chr=$1
  start=$2
  end=$3
  
  
  if (start <= 1000) {
    new_start = end
    new_end = end + pad
  } 
  
  else {
    raw_start = start - pad
    # Zabrání záporným souřadnicím
    new_start = (raw_start > 0) ? raw_start : 0 
    new_end = start
  }
  
  print chr, new_start, new_end
}' /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-pad_q/inputs/1747537496/q_arm_telomeric.bed > padded.bed
)  > "$out1f05a7e4" 2> "$err1f05a7e4"
echo $? > /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-pad_q/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-pad_q/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-pad_q/execution
sync


)
mv /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-pad_q/execution/rc.tmp /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-pad_q/execution/rc
