#!/bin/bash

cd /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-p_arm_identity/execution
tmpDir=$(mkdir -p "/cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-p_arm_identity/tmp.163a17ee" && echo "/cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-p_arm_identity/tmp.163a17ee")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-p_arm_identity/execution

)
out1f05a7e4="${tmpDir}/out.$$" err1f05a7e4="${tmpDir}/err.$$"
mkfifo "$out1f05a7e4" "$err1f05a7e4"
trap 'rm "$out1f05a7e4" "$err1f05a7e4"' EXIT
touch '/cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-p_arm_identity/execution/stdout' '/cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-p_arm_identity/execution/stderr'
tee '/cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-p_arm_identity/execution/stdout' < "$out1f05a7e4" &
tee '/cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-p_arm_identity/execution/stderr' < "$err1f05a7e4" >&2 &
(
cd /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-p_arm_identity/execution


set -euo pipefail

awk 'BEGIN{OFS="\t"} 
{
  # $1 = query chrom
  # $6 = target chrom
  # $10 = percent identity
  key = $1"\t"$6"\t"$10
  if(!seen[key]++) {
    print $1, $6, $10
  }
}' /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-p_arm_identity/inputs/841353551/alignment.paf > pairwise_identity.txt
)  > "$out1f05a7e4" 2> "$err1f05a7e4"
echo $? > /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-p_arm_identity/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-p_arm_identity/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-p_arm_identity/execution
sync


)
mv /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-p_arm_identity/execution/rc.tmp /cromwell-executions/subtelomeric_project/1f05a7e4-c1ad-4559-b1c1-422ee648bd8c/call-p_arm_identity/execution/rc
